platform :ios, '11.0'
use_frameworks!

pod 'RideOsApi', :git => 'https://github.com/rideOS/rideos-api-ios.git', :tag => '0.1.2'

pod 'SwiftFormat/CLI', '0.40'
pod 'SwiftLint', '0.32.0'

def ride_os_common
  pod 'RideOsCommon', :path => '../'
end

def common_test_pods
  pod 'RxTest', '4.4.1'
  pod 'Cuckoo', '1.1.1'
end

target 'RideOsTestHelpers' do
  ride_os_common
  common_test_pods
end

target 'RideOsCommonTests' do
  ride_os_common
  common_test_pods
end

target 'RideOsRiderTests' do
  pod 'RideOsRider', :path => '../'
  common_test_pods
end

target 'RideOsDriverTests' do
  pod 'RideOsDriver', :path => '../'
  common_test_pods
end

target 'RideOsHereMapsTests' do
  pod 'RideOsHereMaps', :path => '../'
  common_test_pods
end

target 'RideOsGoogleMapsTests' do
  pod 'RideOsGoogleMaps', :path => '../'
  common_test_pods
end
